name: mlops-local

services:
  # MLflow Tracking Server
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.8.0
    container_name: mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlruns
      --allowed-hosts "*"
    ports:
      - "5000:5000"
    volumes:
      - mlflow-db:/mlflow
      - mlflow-artifacts:/mlruns
    networks:
      - mlops-net

  # FastAPI Inference API
  api:
    build:
      context: .
      dockerfile: service/model-api/Dockerfile
    container_name: housing-api
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - mlflow-artifacts:/mlruns
    depends_on:
      - mlflow
      - train
    networks:
      - mlops-net

  # Training Job
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: housing-train
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - ./data:/app/data
      - mlflow-artifacts:/mlruns
    depends_on:
      - mlflow
    networks:
      - mlops-net

networks:
  mlops-net:
    driver: bridge

volumes:
  mlflow-artifacts:
  mlflow-db: